name: Learning Showcase → README

on:
  schedule:
    # Every Friday 18:00 UTC (14:00 Toronto, adjusts with DST automatically)
    - cron: '0 18 * * FRI'
  workflow_dispatch:

jobs:
  inject:
    runs-on: ubuntu-latest
    env:
      # MODE=latest → pick newest file by date prefix
      # MODE=random → pick a random file each run
      MODE: latest
      FOLDER: showcase
      README: README.md
      START: "<!-- SHOWCASE_START -->"
      END: "<!-- SHOWCASE_END -->"

    steps:
      - uses: actions/checkout@v4

      - name: Ensure showcase folder exists
        run: |
          if [ ! -d "$FOLDER" ]; then
            echo "::error::Folder '$FOLDER' not found. Create it and add *.md files."
            exit 1
          fi
          ls -1 "$FOLDER"/*.md 2>/dev/null || { echo "::error::No markdown files in $FOLDER/"; exit 1; }

      - name: Pick showcase file
        id: pick
        shell: bash
        run: |
          set -euo pipefail
          if [ "${MODE}" = "random" ]; then
            file=$(ls -1 "${FOLDER}"/*.md | shuf -n1)
          else
            # default: pick newest by YYYY-MM-DD prefix
            file=$(ls -1 "${FOLDER}"/*.md | sort -r | head -n1)
          fi
          echo "Chosen → $file"
          echo "FILE=$file" >> "$GITHUB_OUTPUT"

      - name: Inject into README
        shell: bash
        run: |
          set -euo pipefail
          starfile="${{ steps.pick.outputs.FILE }}"
          newblock="$(cat "$starfile")"

          # Insert newblock between START and END markers
          awk -v s="$START" -v e="$END" -v b="$newblock" '
            $0~s{print; print ""; print b; print ""; skip=1; next}
            $0~e{skip=0}
            skip==0{print}
          ' "$README" > README.tmp
          mv README.tmp "$README"

          # Update timestamp line if present (keeps your minimal vibe)
          if grep -q "Last updated:" "$README"; then
            sed -i 's/Last updated: .*<\/sup>/Last updated: '"$(date -u)"'<\/sup>/' "$README"
          fi

      - name: Commit & push
        run: |
          git config user.name  github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add "$README"
          git commit -m "docs: rotate Learning Showcase → README" || echo "no changes"
          git push
